= Argo
:favicon:
:source-highlighter: rouge
:icons: font
// :toc: left
:toclevels: 1
:description: Argo is an open source JSON parser and generator compliant with RFC 7159 written in Java.  It offers document, push, and pull APIs.
:source-roots: {docfile}/../java

Argo is a free, open source JSON parsing and generating library for Java.

Argo is compliant with https://datatracker.ietf.org/doc/html/rfc8259[RFC 8259].
It works with Java 5 onwards, and includes JPMS module information for Java 9 onwards.
Argo has no dependencies.  It's licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache 2 License].

== Downloads

Argo is published on https://central.sonatype.com/artifact/net.sourceforge.argo/argo[Maven Central].

[tabs]
====
Gradle (Kotlin)::
+
--
[source,kotlin,subs="+attributes"]
----
dependencies {
    implementation(group = "net.sourceforge.argo", name = "argo", version = "{revnumber}")
}
----
--

Gradle (Groovy)::
+
--
[source,groovy,subs="+attributes"]
----
dependencies {
    implemenation group: 'net.sourceforge.argo', name: 'argo', version: '{revnumber}'
}
----
--

Maven::
+
--
[source,xml,subs="+attributes"]
----
<dependency>
    <groupId>net.sourceforge.argo</groupId>
    <artifactId>argo</artifactId>
    <version>{revnumber}</version>
</dependency>
----
--
====

== Usage

Let's generate a JSON document to represent a blog entry.

[source,java]
----
include::{docfile}/../../java/argo/ExamplesTest.java[tags=generateSomeJson,indent=0]
----

<1> Static factory methods in `argo.jdom.JsonNodeFactories` model JSON

Our blog entry JSON looks like this:

[source,json]
----
include::{docfile}/../../java/argo/ExamplesTest.java[tags=generateSomeJsonResult,indent=0]
----

To retrieve the title from the blog entry JSON we produced, we parse it, and then extract the value of the `title` field.

[source,java]
----
include::{docfile}/../../java/argo/ExamplesTest.java[tags=parseSomeJson,indent=0]
----

=== Streaming

Suppose we want to add an array of comments retrieved from a data source to our blog entry JSON.
To avoid reading all the comments into memory at once, and to begin outputting JSON text as early as possible, we can use streaming.

[source,java]
----
include::{docfile}/../../java/argo/ExamplesTest.java[tags=streamOutSomeJson;!streamOutSomeJsonIntermediateResultWrapper,indent=0]
----

<1> Get a source of comments
<2> A `StringWriter` for demonstration purposes, but could be any `Writer`
<3> At this point, the `StringWriter` has already received:
+
[source,json]
----
include::{docfile}/../../java/argo/ExamplesTest.java[tags=streamOutSomeJsonIntermediateResult,indent=0]
----
<4> The `Iterable` of comments can be unbounded; our code only keeps one comment in memory at a time

To retrieve the comments from the JSON we just made without having to hold it all in memory, we can use streaming again.

[source,java]
----
include::{docfile}/../../java/argo/ExamplesTest.java[tags=streamInSomeJson,indent=0]
----

<1> A `StringReader` for demonstration purposes, but could be any `Reader`
<2> The stack will keep track of the parents of the current element
<3> Nodes' text is also streamed, so we can have unbounded strings, numbers, and field names

=== Performance tuning

==== Optional whitespace

The computational cost of parsing a JSON document correlates well with its length.  Reducing or eliminating optional whitespace from input JSON reduces its size and results in a roughly proportional reduction in parsing cost.

Similarly, generating JSON with optional whitespace included incurs a processing cost.  By default, Argo generates JSON with optional whitespace to improve readability.  If performance is a greater concern than readability, optional whitespace can be switched off:
[source,java]
----
include::{docfile}/../../java/argo/ExamplesTest.java[tags=enableCompactGeneration,indent=0]
----

==== Buffering

Argo does not add its own buffering to a `Reader` it parses from, or to a `Writer` it generates to.  Parsing from an unbuffered `Reader` that performs poorly when reading single characters and small arrays of characters may be improved by wrapping it in an appropriately sized `BufferedReader`.  Likewise, generating JSON to an unbuffered `Writer` might be improved by wrapping it in a `BufferedWriter` if the underlying `Writer` is unsuited to single character and short `String` writes.

=== Further details

// suppress inspection "AsciiDocLinkResolve"
In-depth details of the API are available in the link:javadoc/[online javadoc].
The project is hosted on https://sourceforge.net/projects/argo[SourceForge].

== Limitations

[cols="h,,,,"]
|===
| |parse |streaming parse |generate |streaming generate

|Characters in a string
|`Integer.MAX_VALUE` - 8
|Unlimited
|`Integer.MAX_VALUE` - 8
|Unlimited

|Characters in a number
|`Integer.MAX_VALUE` - 8
|Unlimited
|`Integer.MAX_VALUE` - 8
|Unlimited

|Elements in an array
|`Integer.MAX_VALUE` - 8
|Unlimited
|`Integer.MAX_VALUE` - 8
|Unlimited

|Fields in an object
|`Integer.MAX_VALUE` - 8
|Unlimited
|`Integer.MAX_VALUE` - 8
|Unlimited

|Nesting depth
|`Integer.MAX_VALUE` / 4
|`Integer.MAX_VALUE` - 8
|Limited by JVM stack (>2900 using 1MB stack)
|Limited by JVM stack (>4000 using 1MB stack)

|===

image::https://sflogo.sourceforge.net/sflogo.php?group_id=245339&type=13["Get Argo at SourceForge.net. Fast,secure and Free Open Source software downloads",align="center",link=https://sourceforge.net/projects/argo]