on: [ push ]
name: CI
jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container:
      image: eclipse-temurin:17.0.17_10-jdk-noble@sha256:37823ac22e65c6248a897229583835089aa06337ba4477a2878533655333f44d
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: ./gradlew buildSrc:build clean build
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Test Reports
          path: |
            build/reports/tests/
            buildSrc/build/reports/tests/